pub mod card_capability;
pub mod bus_interface;
pub mod io_abort;
pub mod io_ready;
pub mod io_enable;
pub mod interrupt_enable;
pub mod interrupt_pending;
pub mod cccr_sdio_revision;
pub mod sd_physical_specification;
